app:
  cors:
    origins: http://localhost:4200,http://localhost:8090
  mds:
    notifications: mds-notifications
    metrics: mds-metrics
  keycloak:
    url: http://localhost:8090
    realm: realm
    admin:
      clientId: admin-cli
      clientSecret: yourSecret...
      username: test
      password: test


server:
  port: 9090
  servlet:
    context-path: /api/v1

spring:
  application:
    name: multiple-databases
  jmx:
    enabled: false
  datasource:
    db1:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://mds-network:5432/mds1
      username: postgres
      password: postgres
    db2:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://mds-network:5432/mds2
      username: postgres
      password: postgres
    hikari:
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1800000
      maximum-pool-size: 10
      pool-name: HikariCP
  kafka:
    bootstrap-servers: localhost:9092,localhost:9093
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      bootstrap-servers: localhost:9092
      group-id: consumerGroup
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        ddl-auto: update
        #show_sql: true
        #format_sql: true
        #use_sql_comments: true
  websocket:
    enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/realms/mds-realm
springdoc:
  default-produces-media-type: application/json
logging:
  level:
    org:
#      apache:
#        kafka: DEBUG
      springframework:
        security: INFO
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n"
